ignoredBuiltDependencies:
  - extract-file-icon
  - node-window-manager

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - dprint
  - electron
  - electron-winstaller
  - esbuild
  - ffi-napi
  - ref-napi
  - sharp
  - uiohook-napi
  - unrs-resolver
