ignoredBuiltDependencies:
  - extract-file-icon
  - node-window-manager

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - dprint
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - unrs-resolver
